In [1]:
import numpy as np

def main(): 
    # define a vector 
    u = np.array([7, 3, 5])
    print(u)
    print()
    
    # get the size of the vector
    print("length of vector:", len(u))
    print("norm of vector:", np.linalg.norm(u))
    print()
    
    # define a matrix
    A = np.matrix([[4, 9, 2], [3, 5, 7], [8, 1, 6]])
    print(A)
    print("norm of A:", np.linalg.norm(A))
    print("shape of A:", A.shape)
    print("rows of A:", A.shape[0])
    print("columns of A:", A.shape[1])
    print()
    
    # get the transpose of the matrix
    W = A.transpose()
    print("transpose of A:\n", W)
    
    # matrix multiply
    print("A:\n", A)
    print("transpose of A:\n", W)
    Q = W * A
    print("A * transpose of A:\n",Q)
    print()
    
    # dot product
    u = np.array([4, 9, 2])
    print("matrix u:\n", u)
    v = np.array([3, 5, 7])
    print("matrix v:\n", v)
    w = np.dot(u, v)
    print("dot product of u and v:\n", w)
    print()
    
    # cross product
    w = np.cross(u, v)
    print("u x v:\n",w)
    w = np.cross(v, u)
    print("v x u:\n",w)
    
main()

[7 3 5]

length of vector: 3
norm of vector: 9.1104335791443

[[4 9 2]
 [3 5 7]
 [8 1 6]]
norm of A: 16.881943016134134
shape of A: (3, 3)
rows of A: 3
columns of A: 3

transpose of A:
 [[4 3 8]
 [9 5 1]
 [2 7 6]]
A:
 [[4 9 2]
 [3 5 7]
 [8 1 6]]
transpose of A:
 [[4 3 8]
 [9 5 1]
 [2 7 6]]
A * transpose of A:
 [[ 89  59  77]
 [ 59 107  59]
 [ 77  59  89]]

matrix u:
 [4 9 2]
matrix v:
 [3 5 7]
dot product of u and v:
 71

u x v:
 [ 53 -22  -7]
v x u:
 [-53  22   7]


In [ ]:
# overdetermined systems --> use all the solutions in the equations 
# n + m solutions --> n solutions, where n = number of variables 

# we talked about transformations 
## forgot the names: stretching vertically and horizontally, rotation 

In [ ]:
from vpython import *
def main():
    # define constants
    G = 6.67408e-11
    
    # mass of the sun 
    m_sun = 1.9891e30
    
    # radius of the sun (not to scale)
    # r_sun = 6.9634e8 (if to scale)
    r_sun = 5e10
    
    # mass of earth 
    m_earth = 5.972e24
    
    #radius of the earth (not to scale)
    #r_earth = 6.367e6 (if to scale)
    r_earth = 1e10
    
    # create the objects 
    sun = sphere(pos= vector(0,0,0), radius = r_sun, color = color.yellow)
    earth = sphere(pos = vector(1.496e11, 0, 0), radius = r_earth, color = color.blue, make_trail = True)
    
    earth.velocity = vector(0, 3e4, 0)
    
    # define an initial time 
    t = 0
    
    # define a time interval
    dt = 3600
    
    while (t <1e10):
        rate(3000)
        earth.pos = earth.pos + earth.velocity * dt
        r_vector = earth.pos - sun.pos
        F_grav = -(G * m_sun * m_earth / (mag(r_vector)**2)) * (norm(r_vector))
        earth.velocity = earth.velocity + (F_grav/m_earth)*dt
        t += dt
main()  

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>